allthingsclowd/web_page_counter

- scripts/consul.sh
this is required to make sure consul + background get to run
> add sleep to consul

- scripts/install_consul.sh
```
consul01: Success! Data written to: REDIS_MASTER_IP
consul01: Success! Data written to: REDIS_MASTER_NAME
consul01: Success! Data written to: REDIS_SLAVE_IP
consul01: Success! Data written to: REDIS_SLAVE_NAME
consul01: Success! Data written to: REDIS_MASTER_PASSWORD
consul01: Success! Data written to: REDIS_SLAVE_PASSWORD
consul01: Success! Data written to: REDIS_HOST_PORT
consul01: Success! Data written to: GO_DEV_IP
consul01: Success! Data written to: GO_DEV_NAME
consul01: Success! Data written to: GO_REPOSITORY
consul01: Success! Data written to: GO_GUEST_PORT
consul01: Success! Data written to: GO_HOST_PORT
consul01: Success! Data written to: NGINX_NAME
consul01: Success! Data written to: NGINX_IP
consul01: Success! Data written to: NGINX_GUEST_PORT
consul01: Success! Data …
```
> add initital var.env to consul kv

- conf/vault.hcl
- scripts/install_consul.sh
- scripts/install_vault.sh
and move vault to use local client
> change consul to allow clients 0.0.0.0

- conf/vault.hcl
- scripts/install_consul.sh
- scripts/install_vault.sh
refactor to be able to spin a consul cluster in travis
> some tweaks

- scripts/install_consul.sh
travis working but vagrant failing - must have screwed up a merge :(
All back to a known good state now!!!
> Fix vagrant

- Vagrantfile
- conf/nomad.d/client.hcl
- nomad_job.hcl
- scripts/install_Go_app.sh
- scripts/install_nomad.sh
> basic setup for nomad

- .travis.yml
typo - missing '/' in path
5 minutes
> fixed path

- .travis.yml
- scripts/install_Go_app.sh
- scripts/travis_run_go_app.sh
configuring incorrect file
30 minutes
> Update correct travis build file

- .travis.yml
Add template files to release deployment
Copies al files necessary to run the binary to the release
modified the .travis.yml to include the ailes located in the templates directory
30 minutes
> Add template files to release deployment

- readme.md
> Tidying Up ReadME

- readme.md
> New Feature Requirements or Refactors Added to Readme

- scripts/install_vault.sh
Upgrade Vault to version 0.11.0
Upgrade Vault to version 0.11.0
modified vault binary version in install_vault.sh
2 minutes
> Update Vault Version to 0.11.0

- conf/nginx.ctpl
- nomad_job.hcl
> nomad updates

- nomad_job.hcl
- scripts/install_Go_app.sh
> updated hcl

- scripts/install_SecretID_Factory.sh
Ensured travis used local ip for consul calls
> travis fix

- Vagrantfile
- packer/template.json
- scripts/install_SecretID_Factory.sh
- scripts/install_consul.sh
- scripts/install_dd_agent.sh
- scripts/install_nomad.sh
- scripts/install_redis.sh
- scripts/install_webserver.sh
- scripts/packer_install_base_packages.sh
Added missing binaries from base packages
Added unzip, curl, jq to base image and renamed to web-page-counter
Modified packer installation scripts
1 hour to upload new image
> Updated packer build

- scripts/install_Go_app.sh
ongoing tidy up
removes old refs to embedded html templates that have been stripped out
deleted a line
3 minutes
> remove old refs to html templates

- main.go
- scripts/install_webserver.sh
> Added preflight options to all routes

- 1
- Vagrantfile
- main.go
> Add allow cache control header

- 1
- main.go
> More cors tweaks to allow cache control

- readme.md
Added new Angular (6) SPA front end code which is servered from the nginx proxy server
Provides separation between frontend and backend code
SPA provides mechanism form better UX during demo of HashiCorp Infrastructure features
Use Angular 6 getting started guide - very rapid process - quite impressive cli
`ng generate...`
3 long days - includes sorting out CORS issues
> FrontEnd BackEnd Code Separation

- .travis.yml
- main.go
- readme.md
- scripts/install_Go_app.sh
- scripts/install_SecretID_Factory.sh
- scripts/install_consul.sh
- scripts/install_nomad.sh
- scripts/install_redis.sh
- scripts/install_vault.sh
- scripts/install_webserver.sh
- scripts/packer_configure_vagrant_user.sh
- scripts/packer_install_base_packages.sh
Noisey console deployment
Use quiet option on tools to remove unnecessary cruft from display
changed all `wget` to `wget -s`
10 minutes
> added quiet wget

- scripts/install_consul.sh
CONSUL Update
Update consul to version 1.3
30 sec
> Updated to consul 1.3

- conf/nomad.d/nomad.hcl
- conf/vault.d/vault.hcl
- docs/vagrant/ReadMe.md
- docs/vault/ReadMe.md
- scripts/nomad_job.hcl
- var.env
> Updating documentation

- conf/nomad.d/nomad.hcl
- conf/vault.d/vault.hcl
- scripts/install_SecretID_Factory.sh
- scripts/install_go_app.sh
- scripts/install_webserver.sh
- scripts/nomad_job.hcl
- var.env
Github release downloads failing...
Modify download scripts to follow redirects on URLs
Add -L parameter to curl requests
60 minutes (including debug)
> updated for github redirects

- Vagrantfile
- conf/nomad.d/nomad.hcl
- conf/vault.d/vault.hcl
- packer/template.json
- scripts/packer_install_base_packages.sh
- test/ImageBuild/controls/webpagecounter.rb
- var.env
Updated to Consul 1.6
Updated to Consul 1.6
Ensure packer can deploy virtualbox/vmware/azure images from single deployment
quick mods
30 minutes
> Consul binary update

- scripts/install_golang.sh
> fix go path

- conf/nomad.d/nomad.hcl
- conf/vault.d/vault.hcl
- scripts/install_go_app.sh
- scripts/nomad_job.hcl
- var.env
> Add certificate authority file to host web counter app servers

- scripts/packer_install_base_packages.sh
- test/ImageBuild/controls/webpagecounter.rb
- var.env
Update to latest binary releases
5 minutes
> Binary updates

- ReadMe.md
- scripts/install_consul.sh
Added UDP traffic encryption
Encrypts UDP network traffic
Added encrypt parameter to consul configuration 
Used consul keygen to create the encryption key
15 minutes
> Add consul udp encryption

- scripts/packer_install_base_packages.sh
- test/ImageBuild-Travis/controls/webpagecounter.rb
- var.env
New Binaries Released - Updated Tests and Vars file
20 minutes to rebuild images
> revved binaries and tests
